import Head from 'next/head';
import Image from 'next/image';
import clsx from 'clsx';
import Footer from '../Components/Footer';
// import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={clsx('bg-[#FDF6EC]')}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main
        className={clsx(
          'min-h-screen',
          'px-8',
          'py-16',
          'flex',
          'flex-col',
          'justify-center',
          'items-center',
          'text-gray13',
          'selection:bg-gray6'
        )}
      >
        <div className={clsx('max-w-[600px]')}>
          <h1 className={clsx('text-lg')}>Hey Sahishnu 👋🏽</h1>
          <p className={clsx('')}>
            Lets see how your organization is feeling today...
          </p>
        </div>
        <div className={clsx('max-w-[600px]', 'bg-white', 'rounded-lg', 'p-4')}>
          <h2 className={clsx('')}>Trends</h2>
          <p>Here is a breakdown of how your teams are trending</p>
          <div>Graph here</div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
